//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timexis_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveInfo
    {
        public int LeaveInfoID { get; set; }
        public string DayOfWeek { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public int LeaveTypeID { get; set; }
        public string HolidayName { get; set; }
    
        public virtual Leave Leave { get; set; }
    }
}
